services:
  frontend:
    restart: always
    container_name: frontend
    volumes:
      - ./:/app
      - /app/node_modules
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    ports:
      - "5173:5173"
